spring: 
  application: 
    name: web
  h2: 
    console: 
      enabled: true
  thymeleaf:
    prefix: classpath:/web/
    suffix: .html
  profiles: 
    active: file
  http: 
    multipart: 
      maxFileSize: 1024Mb
      maxRequestSize: 1024Mb
  datasource:
    url: jdbc:h2:${PAS_HOME}/config/pas-authentication
    userName: pas-web
    password: pas-web
    driver-class-name: org.h2.Driver
#    sql-script-encoding: utf-8
#    schema: classpath:db/schema.sql
mybatis:
  configuration:
    cache-enabled: true
server:
  port: 8080
  context-path: /
#  context-path: /api/
h2:
  tcp:
    port: 9092
  web:
    port: 9090
#ddbs: 
#  urlList: 172.16.6.135,172.16.6.136,172.16.6.137
#  bucket: demo
#  bucketPassWord: wowangle
analysis: 
  pasHome: ${PAS_HOME}
  uploadRoot: ${PAS_HOME}/upload/
  logPath: ${PAS_HOME}/logs
eureka:
  defaultZone: http://localhost:8761/eureka
  LeaseRenewalIntervalInSeconds: 30
  RegisterWithEureka: false
  FetchRegistry: false
ddbs: 
  url: 172.16.6.136
  bucket: pas-web
  bucketPassWord: 
store:
  type: file